version: "3"

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rt-database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      LANG: C.UTF-8
    ports:
      - "3308:3306"
    restart: always
