package model

enum class OrderStatus(val value: Long) {
    STATUS_NEW(1L),
    STATUS_INVALID(2L),
    STATUS_PREPARED(3L),
    STATUS_IN_PROGRESS(4L),
    STATUS_COORDINATION_FINISHED(5L),
    STATUS_CANCELLED_BY_CUSTOMS(6L),
    STATUS_CANCELLED(7L),
    STATUS_FINISHED(8L),
    STATUS_CONSOLIDATED(96L),
    STATUS_REJECTED(97L),
    STATUS_CREATED(98L),
    STATUS_REGISTERED(99L),
    STATUS_COMPLIANCE_CHECK_FAILED(100L);
}
